

export const ADD_DATA_REQUEST = 'ADD_DATA_REQUEST'
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS'
export const ADD_DATA_FAIL = 'ADD_DATA_FAIL'
export const ADD_DATA_RESET = 'ADD_DATA_RESET'




