export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const Register_REQUEST = 'Register_REQUEST'
export const Register_SUCCESS = 'Register_SUCCESS'
export const Register_FAIL = 'Register_FAIL'


export const DASHBOARD_DATAINFO_REQUEST = 'DASHBOARD_DATAINFO_REQUEST'
export const DASHBOARD_DATAINFO_SUCCESS = 'DASHBOARD_DATAINFO_SUCCESS'
export const DASHBOARD_DATAINFO_FAIL = 'DASHBOARD_DATAINFO_FAIL'
export const DASHBOARD_DATAINFO_RESET = 'DASHBOARD_DATAINFO_RESET'



export const USER_LOGOUT = 'USER_LOGOUT'



